### PR TITLE
feat: Update repository structure

### PR DESCRIPTION
**Pull request by Ehsan-saradar**
## Description

1. Remove the `official` directory and move the marketplace app to the root folder.
2. Add the `app.ignite.yml` file, which contains the necessary information for the marketplace app to index applications inside this repository.
3. Update `go.work.example`.
4. Bump ignite version to `v28.2.0`.

### CODE REVIEW

**Comment by jeronimoalbi** [comment]
@Ehsan-saradar, should #32 be merged before this PR? If so then maybe this PR should stay in Draft until then

**Comment by jeronimoalbi** [comment]
There are a couple of files that need merging but otherwise looks good 👍

**Comment by toschdev** [comment]
I don't support the `official` directory. Every app listed in this repository should be considered official. But the extra directory clutters the namespace during installation. Community submissions should be expected to be hosted on designated accounts and repositories provided by them.

**Comment by Pantani** [comment]
Can we not use the official folder? All apps will be official if we review and start to maintain them in our repo. If not approved, the user can use he's repository.

wdyt @jeronimoalbi @ilgooz @julienrbrt?

**Comment by Ehsan-saradar** [comment]
> Can we not use the official folder? All apps will be official if we review and start to maintain them in our repo. If not approved, the user can use he's repository.

I totally get your point and actually had the same idea (and I still think it's more convenient). But, @ilgooz  suggested this structure.

**Comment by Pantani** [comment]
> > Can we not use the official folder? All apps will be official if we review and start to maintain them in our repo. If not approved, the user can use he's repository.
> 
> I totally get your point and actually had the same idea (and I still think it's more convenient). But, @ilgooz suggested this structure.

@ilgooz, do we have any particular reason for the official directory? IMHO since the most of the team agree to not use, we can avoid the `official` folder

**Comment by Pantani** [comment]
> > Can we not use the official folder? All apps will be official if we review and start to maintain them in our repo. If not approved, the user can use he's repository.
> 
> I totally get your point and actually had the same idea (and I still think it's more convenient). But, @ilgooz suggested this structure.

@toschdev also strongly agree in the structure

**Comment by toschdev** [comment]
@Pantani I'm thinking more about the user. Do we want them to type

`ignite app install github.com/ignite/apps/hermes` or 
`ignite app install github.com/ignite/apps/official/hermes` 

where the second one is longer and also harder to remember. 
Every app in this repo should be considered official IMO

**Comment by julienrbrt** [comment]
100% agree with the above arguments.

**Comment by julienrbrt** [comment]
Looks like marketplace is still under `official`

**Pull request merged**
